// Explicit source order for an EMPTY database with Supabase auth/extensions
// primitives already installed. This is not a live migration runner.
export const CANONICAL_FRESH_INSTALL_V3 = Object.freeze([
  '001_profiles.sql',
  '002_core_erp_tables_mvp.sql',
  '003_patch_core_tables_missing_sync_columns.sql',
  '005_sales_orders_sync.sql',
  '006_dashboard_category_images.sql',
  '004_rls_viewer_policies.sql',
  '008_add_default_costs_to_product_variants.sql',
  '009_public_read_only_policies.sql',
  '010_inventory_items.sql',
  '011_fix_rls_helper_functions.sql',
  '012_public_read_only_remaining_tables.sql',
  '014_upgrade_inventory_items_composite_key.sql',
  '015_japan_packages_tables.sql',
  '016_bundle_components.sql',
  '017_outbound_shipments.sql',
  '018_cloud_import_batch_canonical.sql',
  '018b_cloud_import_batch_acl_compatibility_repair.sql',
  '020_cloud_field_cas.sql',
  '021_purchase_batch_transaction_idempotency.sql',
  '023_cloud_atomic_json_restore.sql',
  '024_cloud_restore_snapshot_export.sql',
  '025_cloud_atomic_restore_execution_timeout.sql',
  '026_cloud_restore_guarded_full_delete.sql',
  '026b_cloud_inventory_uuid_identity_bridge.sql',
  '027_cloud_restore_safeupdate_compatible_delete.sql',
  '029_cloud_restore_live_schema_alignment.sql',
  '030_cloud_restore_cross_environment_audit_identity_portability.sql',
  '031_japan_package_receiving_atomic_transaction.sql',
  '032_outbound_shipment_atomic_delete.sql',
  '033_outbound_status_transition_timestamp.sql',
  '034_japan_package_partial_receiving_state_machine.sql',
  '035_cloud_restore_cross_environment_effective_path.sql',
  '036_cloud_restore_final_closure.sql',
  '037_cloud_restore_row_shape_fix.sql',
  '038_cloud_restore_durable_attempt_envelope.sql',
  '039_cloud_restore_integrity_audit.sql',
  '040_cloud_restore_owner_builder_proof.sql',
  '041_cloud_restore_durable_failure_recovery.sql',
  '042_cloud_restore_durable_execution_closure.sql',
  '043_cloud_restore_execute_dispatch_boundary.sql',
  '044_waca_cloud_ledger.sql',
  '045c_waca_cloud_atomic_restore_semantic_closure.sql',
  '046_waca_myacg_parent_evidence.sql',
  '046b_waca_myacg_parent_compatibility_repair.sql',
  '047_erp_schema_migration_ledger.sql',
  '048_erp2_live_canonical_contract_reconciliation.sql',
  '049_private_order_atomic_transaction.sql',
  '050_catalog_atomic_transaction.sql',
  '051_related_saveability_atomic_transactions.sql',
  '052_waca_master_link_delta_merge.sql',
  '053_outbound_status_changed_at_restore_compatibility.sql',
  '054_authoritative_backup_json_aggregation.sql',
  '055_authoritative_backup_json_transport.sql',
  '056_catalog_materialized_purchase_projection.sql',
  '057_atomic_restore_staged_execution_and_validation.sql',
  '058_restore_execute_generation_and_typed_stage.sql',
  '059_restore_typed_stage_dashboard_compatibility.sql',
  '060_restore_prepare_bounded_finalize.sql',
  '061_restore_prepare_single_pass_json.sql',
  '062_restore_resource_stage_and_projected_proof.sql',
  '063_restore_prepare_draft_proof_initialization.sql',
  '064_restore_bounded_chunk_batch_and_identity_profile.sql',
  '065_cloud_backup_stable_readonly_execution.sql',
  '066_restore_prepare_set_based_resource_staging.sql',
  '067_restore_begin_independent_bounded_ops_cleanup.sql',
  '068_restore_ops_conservative_batch_envelope.sql',
]);

// Checksum-bearing source history. These artifacts remain reviewable and are
// ordered for reconciliation, but failed/superseded entries are never executed
// by the canonical fresh-install chain above.
export const ERP2_MIGRATION_SOURCE_ORDER_V3 = Object.freeze([
  ...CANONICAL_FRESH_INSTALL_V3.slice(0,
    CANONICAL_FRESH_INSTALL_V3.indexOf('045c_waca_cloud_atomic_restore_semantic_closure.sql')),
  '045_waca_cloud_atomic_restore_closure.sql',
  '045b_waca_cloud_atomic_restore_compatibility_repair.sql',
  '045c_waca_cloud_atomic_restore_semantic_closure.sql',
  '046_waca_myacg_parent_evidence.sql',
  '046b_waca_myacg_parent_compatibility_repair.sql',
  '047_erp_schema_migration_ledger.sql',
  '048_erp2_live_canonical_contract_reconciliation.sql',
  '049_private_order_atomic_transaction.sql',
  '050_catalog_atomic_transaction.sql',
  '051_related_saveability_atomic_transactions.sql',
  '052_waca_master_link_delta_merge.sql',
  '053_outbound_status_changed_at_restore_compatibility.sql',
  '054_authoritative_backup_json_aggregation.sql',
  '055_authoritative_backup_json_transport.sql',
  '056_catalog_materialized_purchase_projection.sql',
  '057_atomic_restore_staged_execution_and_validation.sql',
  '058_restore_execute_generation_and_typed_stage.sql',
  '059_restore_typed_stage_dashboard_compatibility.sql',
  '060_restore_prepare_bounded_finalize.sql',
  '061_restore_prepare_single_pass_json.sql',
  '062_restore_resource_stage_and_projected_proof.sql',
  '063_restore_prepare_draft_proof_initialization.sql',
  '064_restore_bounded_chunk_batch_and_identity_profile.sql',
  '065_cloud_backup_stable_readonly_execution.sql',
  '066_restore_prepare_set_based_resource_staging.sql',
  '067_restore_begin_independent_bounded_ops_cleanup.sql',
  '068_restore_ops_conservative_batch_envelope.sql',
]);

// These historical SQL Editor artifacts are alternative/superseded routes,
// not missing steps that a runner may silently ignore after a failed apply.
export const EXCLUDED_HISTORICAL_ARTIFACTS = Object.freeze({
  '002_erp_tables.sql': 'Superseded core draft; 002_core_erp_tables_mvp and 018 define the canonical schema.',
  '003_sales_orders_migration.sql': 'Superseded by 005_sales_orders_sync.',
  '004_patch_fk_restrict_product_variants.sql': 'Legacy data-cleanup SQL; the core schema already has the RESTRICT FK.',
  '007_create_dashboard_category_images_bucket.sql': 'Unused legacy Storage bucket; no current product dependency.',
  '013_fix_storage_category_images_policies.sql': 'Unused legacy Storage policy; no current product dependency.',
  '028_cloud_restore_schema_aware_safeupdate_delete.sql': 'Alternative inventory_key-PK restore writer; 029 supersedes its final contract.',
  '045_waca_cloud_atomic_restore_closure.sql': 'Failed live attempt preserved as WACA_PATCH_ANCHOR_DRIFT; 045c supersedes it.',
  '045b_waca_cloud_atomic_restore_compatibility_repair.sql': 'Failed live attempt preserved as WACA_045B_SEMANTIC_SOURCE_CONFLICT; 045c supersedes it.',
});
